Dev (#114)
* update pipeline

* upadte pipeline

* update pipeline

* updaet pipeline

* update pipeline

* fix pipeline

* update pipeline

* upadte pipeline

* update pipeline

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -3,38 +3,32 @@ name: Pipeline
 on:
   push:
 
-
-env:
-  isMain: ${{ github.ref == 'refs/heads/main' }}
-  isDev: ${{ github.ref == 'refs/heads/dev' }}
-
-
 jobs:
   verify:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
 
-      - name: "Setup Node"
+      - name: 'Setup Node'
         uses: actions/setup-node@v3
         with:
           node-version: ${{vars.NODE_VERSION}}
           cache: yarn
 
-      - name: "Installing Modules"
+      - name: 'Installing Modules'
         run: yarn install
 
-      - name: "Unit Testing"
+      - name: 'Unit Testing'
         run: yarn test:unit
 
-      - name: "Publish Test Results"
+      - name: 'Publish Test Results'
         uses: mikepenz/action-junit-report@v3
-        if: success() || failure()  # always run even if the previous step fails
+        if: success() || failure() # always run even if the previous step fails
         with:
           report_paths: '**/reports/junit.xml'
           fail_on_failure: true
 
-      - name: "Publish Code Coverage"
+      - name: 'Publish Code Coverage'
         uses: 5monkeys/cobertura-action@master
         if: ${{github.event_name == 'pull_request' }}
         with:
@@ -47,30 +41,34 @@ jobs:
     uses: ./.github/workflows/build-and-publish.template.yaml
     needs: verify
     with:
-      nodeEnvironment: "print"
-      pushImages: ${{ github.ref == 'refs/heads/main' }}
+      nodeEnvironment: 'print'
+      pushImages: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
+      suffix: ${{ github.ref == 'refs/heads/main' && '_main' || github.ref == 'refs/heads/dev' && '_dev' || '' }}
     secrets: inherit
 
   build_dev:
     uses: ./.github/workflows/build-and-publish.template.yaml
     needs: verify
     with:
-      nodeEnvironment: "dev"
-      pushImages: ${{ github.ref == 'refs/heads/main' }}
+      nodeEnvironment: 'dev'
+      pushImages: ${{ github.ref == 'refs/heads/dev' }}
+      suffix: ${{ github.ref == 'refs/heads/main' && '_main' || github.ref == 'refs/heads/dev' && '_dev' || '' }}
     secrets: inherit
 
   build_prelive:
     uses: ./.github/workflows/build-and-publish.template.yaml
     needs: verify
     with:
-      nodeEnvironment: "prelive"
-      pushImages: ${{ github.ref == 'refs/heads/main' }}
+      nodeEnvironment: 'prelive'
+      pushImages: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
+      suffix: ${{ github.ref == 'refs/heads/main' && '_main' || github.ref == 'refs/heads/dev' && '_dev' || '' }}
     secrets: inherit
 
   build_main:
     uses: ./.github/workflows/build-and-publish.template.yaml
     needs: verify
     with:
-      nodeEnvironment: "prod"
+      nodeEnvironment: 'prod'
       pushImages: ${{ github.ref == 'refs/heads/main' }}
+      suffix: ${{ github.ref == 'refs/heads/main' && '_main' || github.ref == 'refs/heads/dev' && '_dev' || '' }}
     secrets: inherit
